steps:
  - id: "Executando testes"
    name: 'gcr.io/cloud-builders/go:alpine'
    args: ['test', '.']
    env: ['GOPATH=.']
    dir: './src'

  - id: "Executando a Soma"
    name: 'gcr.io/cloud-builders/go:alpine'
    args: ['run', '.']
    env: ['GOPATH=.']
    dir: './src'