steps:
  - id: "Executando Instalação"
    name: 'gcr.io/cloud-builders/go'
    args: ['install', 'projeto_go']
    env: ['GOPATH=.']

  - id: "Executando testes"
    name: 'gcr.io/cloud-builders/go:alpine'
    args: ['test', 'projeto_go']
    env: ['GOPATH=.']

  - id: "Criando imagem"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/projeto_go', '.']
images: ['gcr.io/$PROJECT_ID/projeto_go']